import { VerticalBox, Button } from "std-widgets.slint";
export component Animation inherits Rectangle{
    property <bool> isBlue: false;



    property <length> x_grey: isBlue? box_container.width - 30px  :  0px;
    property <length> x_green: isBlue? 0px  :  box_container.width - 30px;
    background: isBlue ? blue : red;
    animate background {
        duration: 350ms;
    }
    animate x_grey {
         duration: 800ms;
    }
    animate x_green {
         duration: 800ms;
    }
    VerticalBox {
    
        label := Text {
            text: "Nothing is clicked";
        }

        box_container := Rectangle {
            width: 100%;
            height: 50px;
            gray_box := Rectangle {
                x: x_grey;
                height: 30px;
                width: 30px;
                z: 1;
                background: gray;
            }

            green_box := Rectangle {
                x: x_green;
                height: 30px;
                width: 30px;
                background: green;
            }
    }
        Button {
            text: "Click Me";
            
            clicked => {
                label.text = " Button clicked";
            }
        }
        Rectangle {
            border-color: #fff;
            border-width: 1px;
            border-radius: 4px;
            height: parent.height*20%;
        area := TouchArea {
            Text{ text: "area";}
            clicked => {
                isBlue = !isBlue;
                label.text="Area clicked!"
            }
        }
    }
    }
}